### ISSUE TITLE
[☂] v1 tasks

### ISSUE THREAD

**Issue by molant** [electron/website#2]
Some tasks from the top of my head:

Pending:

- [ ] Figure out i18n integration (#64)
- [ ] Figure out docs versioning
- [ ] Review and update documentation style guide to match new website.
- [ ] Create new docs landing page (@molant, @erickzhao)
- [ ] Upstream everything we can to `electron/electron`
- [x] Update styles to match a bit more the current live site (@erickzhao)
- [ ] Need to find a way to allow easy merges on `electron/electron` for the `/docs`  folder ➡ Maybe use the CODEOWNERS plugin or similar?

Done:

- [x] Add frontmatter to documentation, should be in electron/electron but maybe we can start doing it here (see #https://github.com/electron/electron/pull/28303)? (@molant) (#3)
- [x] Pull documentation from the right branch as pre-build step (@molant) (#3)
- [x] Automatically generate the sidebar ➡ ~~Haven't found any documentation about it or if it is enough with the right folder structure~~ Looks like we need to generate it somehow or else docusaurus complains with:  (@molant) (#3)
  > Error: Bad sidebars file.
  > These sidebar document ids do not exist:
- [x] Add Fiddle integration in the docs (@erickzhao)
- [x] Remove Blog link for now (#10)
- [x] Deploy the website somewhere (@molant) ➡️  https://beta.electronjs.org/
- [x] Reach out to docsearch see if we can have 2 indexes for the website (@molant) (#22) ➡ **Waiting for next crawl before merging*
- [x] Figure out how to enable fast docs development locally (@molant) (#4)
- [x] List of examples sooner rather than later
- [x] Automatically update/deploy periodically or when there's new content in `electron/electron` (#19 - @molant)
- [x] Add an "Examples"  link to the top nav ➡ Talk about fiddle in the landing page (@molant)
- [x] search feature
- [x] Update electronjs.org-new README
- [x] Document and be clear about acceptance criteria for submissions.
- [x] START HERE URL
- [x] Discord Channel `#TBD`

**Comment by molant** [comment]
Looks like we need to generate it somehow or else docusaurus complains with: 
  > Error: Bad sidebars file.
  > These sidebar document ids do not exist:

**Comment by molant** [comment]
- [ ] Remove Blog link for now
- [ ] Add an "Examples"  link to the top nav

**Comment by molant** [comment]
@erickzhao I've reorganized a bit the top comment and added some new tasks.
What do you think of updating that list to show what we believe should be done to sunset the old docs and just have the new ones?

**Comment by erickzhao** [comment]
Now that we've shipped the whole site to https://electronjs.org, I think we can close this issue. I think this is all done except for Versioned Docs!
